name: Daily ArXiv Digest

on:
  schedule:
    - cron: "5 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: daily-arxiv-digest
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily digest
        env:
          ARXIV_DAILY_CONFIG: config.yaml
        run: |
          python scripts/fetch_arxiv_daily.py

      - name: Commit and push changes
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add outputs from the new config/script schema
          git add config.yaml || true
          git add digests/ topics/ data/ || true

          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Daily digest update"
          git push
